[tool.poetry]
name = "portfolio"
version = "0.1.0"
description = ""
authors = ["wakadorimk2 <moriyamakensetsu@yahoo.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
